default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  host: localhost
  password: password


development:
  <<: *default
  database: organization_api_development

test:
  <<: *default
  database: organization_api_test


production:
  <<: *default
  database: organization_api_production
  username: organization_api
  password: <%= ENV["ORGANIZATION_API_DATABASE_PASSWORD"] %>
